name: Build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        default: dev

jobs:
  build:
    strategy:
      matrix:
        target: [dev, stage, prod]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build project
        run: |
          # Add your build commands here
          echo "Building the project..."
